const QUESTIONS_DB = {
    "history": {
        title: "История языка (History of Language)",
        data: [
            { q: "What is the reconstructed common ancestor of Germanic languages called?", a: ["Proto-Germanic", "Old Norse", "Old Saxon", "Middle Germanic", "Proto-Celtic"] },
            { q: "Which language is the principal representative of East Germanic?", a: ["Gothic", "Burgundian", "Vandalic", "Old Saxon", "Frisian"] },
            { q: "Who translated the Gospels into Gothic?", a: ["Ulfilas", "Snorri Sturluson", "Caesar", "Alfred the Great", "H. Sweet"] },
            { q: "Where did Gothic survive the longest?", a: ["Crimea", "Iceland", "Norway", "Britain", "Denmark"] },
            { q: "What is the early common Scandinavian language called?", a: ["Old Norse", "Old Icelandic", "Old Swedish", "Old Saxon", "Old Danish"] },
            { q: "Which Scandinavian language is considered the most literary in early times?", a: ["Old Icelandic", "Old Swedish", "Old Danish", "Old Norwegian", "Old Faroese"] },
            { q: "Which group does English belong to?", a: ["West Germanic", "North Germanic", "East Germanic", "Celtic", "Italic"] },
            { q: "What linguistic change divides High and Low German?", a: ["The Second (High German) Sound Shift", "The Great Vowel Shift", "The i-mutation", "Runic shift", "Rhine consonant shift"] },
            { q: "Which languages form the Anglo-Frisian subgroup?", a: ["Old English and Old Frisian", "Old Saxon and Old High German", "Old Dutch and Frisian", "Gothic and Vandalic", "Norwegian and Danish"] },
            { q: "Which ancient Celtic language in Gaul was replaced by Latin?", a: ["Gallic", "Brythonic", "Goidelic", "Manx", "Cornish"] },
            { q: "Which Celtic language became extinct in the 18th century?", a: ["Cornish", "Welsh", "Breton", "Irish", "Scottish Gaelic"] },
            { q: "Which people introduced Latin into Britain?", a: ["The Romans", "The Anglo-Saxons", "The Vikings", "The Normans", "The Celts"] },
            { q: "Old English is mainly characterized by what type of grammar?", a: ["Synthetic", "Analytic", "Isolating", "Pidgin-like", "Agglutinative"] },
            { q: "What Old English characters represent the “th” sound?", a: ["þ and ð", "æ and œ", "sc and cg", "f and v", "c and k"] },
            { q: "Which Old English text is considered the best-known epic?", a: ["Beowulf", "The Prose Edda", "The Poetic Edda", "The Chronicle of Bede", "The Odyssey"] },
            { q: "What happened to the Old English vocabulary after the Norman Conquest?", a: ["Much of it disappeared and was replaced by French and Latin words", "It expanded greatly with new Germanic borrowings", "It remained unchanged", "It became more inflected", "It was completely forgotten"] },
            { q: "What sound change turned “sk” into “sh” in Old English?", a: ["Anglo-Saxon consonant shift", "i-mutation", "Second Sound Shift", "Great Vowel Shift", "Celtic shift"] },
            { q: "Which pair illustrates i-mutation results?", a: ["man/men", "king/kings", "tree/trees", "house/houses", "bird/birds"] },
            { q: "What percentage of Anglo-Saxon words survived into Modern English?", a: ["About 15%", "About 50%", "About 75%", "About 30%", "About 1%"] },
            { q: "Which dialect became the main written dialect of Old English?", a: ["West Saxon", "Northumbrian", "Kentish", "Mercian", "East Midlands"] },
            { q: "Which period is known as the time of full inflections?", a: ["Old English", "Middle English", "Modern English", "Post-modern English", "Proto-English"] },
            { q: "Which period saw the greatest reduction of inflections?", a: ["Middle English", "Old English", "Modern English", "Late West Saxon", "Early English"] },
            { q: "Which major event accelerated Middle English changes?", a: ["The Norman Conquest", "The Roman invasion", "The Viking settlement", "The Renaissance", "The Industrial Revolution"] },
            { q: "Which case endings merged due to leveling in Middle English?", a: ["-a, -u, -e, -an, -um", "-ed, -ing", "-tion, -sion", "-er, -est", "-ness, -ship"] },
            { q: "Which pronouns lost most of their forms in Middle English?", a: ["Demonstratives", "Personal pronouns", "Interrogatives", "Reflexives", "Possessives"] },
            { q: "Modern English depends mainly on what grammar feature?", a: ["Word order", "Case endings", "Gender marking", "Inflected adjectives", "Runic symbols"] },
            { q: "Who introduced printing to England?", a: ["William Caxton", "Geoffrey Chaucer", "Alfred the Great", "Daniel Defoe", "Robert Cawdrey"] },
            { q: "When is the beginning of the Modern English period commonly placed?", a: ["1500", "1150", "450", "900", "1700"] },
            { q: "What was a major effect of printing on language?", a: ["Standardization", "More dialect diversity", "Decline of literacy", "Elimination of English", "Increase in runic writing"] },
            { q: "Which factor increased literacy in early Modern England?", a: ["Spread of education", "Decline of printing", "Ban on newspapers", "Isolation of villages", "Reduction of schooling"] },
            { q: "What greatly improved communication in modern times?", a: ["The telegraph", "Runes", "Feudal systems", "Wooden ships", "Monastic scribes"] },
            { q: "Which factor required new vocabulary in the Modern period?", a: ["Growth of specialized knowledge", "Decline of trade", "Reduced literacy", "Return to Latin", "Fewer inventions"] },
            { q: "Why did many 18th-century critics dislike foreign borrowings?", a: ["They feared English would be corrupted", "They loved French too much", "They preferred Celtic terms", "They wanted more German words", "They banned new words entirely"] },
            { q: "Which scholar published the first Old English dictionary?", a: ["William Somner", "Samuel Johnson", "George Hickes", "Richard Mulcaster", "Elyot"] },
            { q: "What was a common reason for defending English in the Renaissance?", a: ["To make knowledge available to all people", "To eliminate Latin entirely", "To replace French in court", "To reject classical learning", "To impose censorship"] },
            { q: "Which Renaissance figure strongly promoted English?", a: ["Richard Mulcaster", "Julius Caesar", "Ulfilas", "Snorri Sturluson", "Ascham"] },
            { q: "Which invention helped spread standardized English?", a: ["The printing press", "The runic alphabet", "The reed pen", "The abacus", "The sundial"] },
            { q: "Which conflict reduced Old English dialect prestige?", a: ["The Norman Conquest", "The Roman invasion", "The Viking raids", "The Black Death", "The Civil War"] },
            { q: "Which text is the oldest surviving Old English poem?", a: ["Cædmon’s Hymn", "Beowulf", "The Wanderer", "The Seafarer", "The Chronicle"] },
            { q: "Which languages influenced English most during Middle English?", a: ["French and Latin", "Celtic and Greek", "Arabic and Hebrew", "Norse and Finnish", "Basque and Dutch"] },
            { q: "What type of change characterizes Modern English grammar?", a: ["Loss of inflections", "Growth of case system", "Return to synthetic grammar", "Gender reinforcement", "Runic revival"] },
            { q: "Which factor unified English dialects in the 19th century?", a: ["Railroads and improved travel", "Isolation of regions", "Decline of newspapers", "Loss of literacy", "Rise of local kings"] },
            { q: "Which event expanded English globally?", a: ["British Empire expansion", "Roman retreat", "Norman invasion", "Black Death", "Union with Denmark"] },
            { q: "Why do new scientific words appear?", a: ["New knowledge needs new terms", "Old words are banned", "Languages decay", "Vocabulary must shrink", "Writers invent at random"] },
            { q: "What does vocabulary reflect?", a: ["The progress of civilization", "Personal preference", "Poetic tradition", "Religious rules", "Military power"] },
            { q: "What was a reason classical scholars opposed vernaculars?", a: ["Fear that learning would decline", "Love of English", "Lack of printing", "Support from merchants", "Desire to simplify study"] },
            { q: "Which period does Beowulf belong to?", a: ["Old English", "Middle English", "Modern English", "Proto-English", "Renaissance English"] },
            { q: "Which Old English dialect has the most surviving texts?", a: ["West Saxon", "Kentish", "Mercian", "Northumbrian", "East Anglian"] },
            { q: "What did the Great Vowel Shift affect?", a: ["Pronunciation of long vowels", "Loss of runes", "Adjective endings", "Case system", "Borrowed words"] },
            { q: "Which Old English feature most contributes to its unfamiliar appearance to modern readers?", a: ["The use of special characters like þ, ð, and æ", "The presence of many French loanwords", "The lack of consonant clusters", "The modern spelling rules", "The use of Arabic script"] }
        ]
    },
    "country": {
        title: "Страноведение (UK, US, NZ)",
        data: [
            { q: "What is the official name of Britain?", a: ["The United Kingdom of Great Britain and Northern Ireland", "The United Kingdom", "Great Britain", "Britain", "The British Isles"] },
            { q: "Where is the United Kingdom situated?", a: ["To the north-west of Europe", "In the centre of Europe", "To the south of Europe", "Far east of Europe", "On the European mainland"] },
            { q: "How many countries does the United Kingdom consist of?", a: ["Four", "Two", "Three", "Five", "Six"] },
            { q: "What is the capital of Scotland?", a: ["Edinburgh", "Glasgow", "Belfast", "Cardiff", "London"] },
            { q: "What is the national emblem of England?", a: ["The rose", "The daffodil", "The thistle", "The shamrock", "The lily"] },
            { q: "Which world-famous landmark is a symbol of London?", a: ["The Tower", "Hyde Park", "London Eye", "Buckingham Palace", "Trafalgar Square"] },
            { q: "Which London museum is famous for galleries like 'Human biology' and 'History of the Earth'?", a: ["Natural History Museum", "British Museum", "National Gallery", "Victoria and Albert Museum", "Science Museum"] },
            { q: "What is the capital city of England?", a: ["London", "Manchester", "Liverpool", "Birmingham", "Leeds"] },
            { q: "What is the flag of England?", a: ["A red cross on a white background", "A white cross on a blue background", "A red dragon on white", "A red rose on green", "Three lions on a shield"] },
            { q: "Which Scottish mountain is the tallest in the British Isles?", a: ["Ben Nevis", "Snowdon", "Cairn Gorm", "Scafell Pike", "Helvellyn"] },
            { q: "What is the official language of Wales alongside English?", a: ["Welsh", "Gaelic", "Scots", "Irish", "Cornish"] },
            { q: "Which Northern Ireland city is the capital and largest city?", a: ["Belfast", "Derry", "Lisburn", "Newry", "Armagh"] },
            { q: "What sport was invented by the English?", a: ["Football", "Golf", "Rugby", "Figure-skating", "Snooker"] },
            { q: "Which plant is a national emblem of Wales?", a: ["Leek", "Rose", "Thistle", "Shamrock", "Daffodil"] },
            { q: "What symbol is used for Scotland?", a: ["Thistle", "Red cross on white background", "Red dragon on green background", "Rose", "Shamrock"] },
            { q: "What is the modern Welsh name for themselves?", a: ["Cymry", "Wales and Welsh", "Walh and Walha", "Brecon and Breconians", "Gwynedd and Gwyneddians"] },
            { q: "Who is Charles Dickens?", a: ["Author", "Scientist", "Politician", "Musician", "Explorer"] },
            { q: "Who was Diana, Princess of Wales?", a: ["Princess of Wales", "Princess of Scotland", "Queen of England", "Prime Minister of UK", "Duchess of Edinburgh"] },
            { q: "Who first entered Wales in 43 AD?", a: ["The Romans", "The Celts", "The Vikings", "The Anglo-Saxons", "The Normans"] },
            { q: "What type of state is Great Britain?", a: ["A constitutional monarchy", "A presidential republic", "An absolute monarchy", "A federal republic", "A socialist state"] },
            { q: "When was the Commonwealth founded?", a: ["In 1949", "In 1936", "In 1953", "In 1981", "In 1997"] },
            { q: "When did Queen Elizabeth II ascend the throne?", a: ["In 1952", "On 2 June 1953", "In 1947", "In 1936", "On 21 April 1926"] },
            { q: "Which body has real political power in the UK?", a: ["The House of Commons", "The House of Lords", "The Monarch", "The Cabinet", "The Prime Minister alone"] },
            { q: "What is the National Curriculum?", a: ["A compulsory set of subjects studied up to the age of 16", "A special program only for grammar schools", "An exam taken at universities", "A private school curriculum", "A curriculum only for independent schools"] },
            { q: "What is the GCSE?", a: ["The General Certificate of Secondary Education", "A university entrance diploma", "A primary school certificate", "A private school qualification", "A certificate for teachers"] },
            { q: "What is the purpose of A-levels?", a: ["They are the main standard for university entrance", "They replace GCSE exams", "They allow students to leave school at 14", "They are only for private school pupils", "They are required to enter primary school"] },
            { q: "Which school is world-famous as an independent public school?", a: ["Eton", "Oxford College", "Cambridge Modern School", "Manchester High School", "Brighton Academy"] },
            { q: "What did the Parliament Act 1911 do?", a: ["It restricted the powers of the House of Lords", "It abolished the House of Lords", "It created the Supreme Court", "It gave equal powers to both Houses", "It allowed the monarch to veto bills freely"] },
            { q: "How long is the maximum duration of a UK Parliament according to the modern rules?", a: ["Five years", "Three years", "Seven years", "Ten years", "Two years"] },
            { q: "What type of monarchy does the United Kingdom have?", a: ["A constitutional monarchy", "An absolute monarchy", "A federal monarchy", "A republican monarchy", "A ceremonial empire"] },
            { q: "When did King George V change the name of the royal family to “Windsor”?", a: ["On 17 July 1917", "In 1882", "In the first world war era", "When German blimps bombed London", "After Queen Victoria's reign"] },
            { q: "Where did Joanne K. Rowling live when she was a small girl?", a: ["In Winterbourne", "In London", "In Cambridge", "In Westminster", "In Bristol"] },
            { q: "When was Alan Milne born?", a: ["On 18 January 1882", "On 17 July 1917", "In the year Harry Potter was introduced", "At the age of 11", "At the age of 24"] },
            { q: "Where was William Shakespeare born?", a: ["In Stratford-on-Avon", "In London", "In Oxford", "In Manchester", "In Liverpool"] },
            { q: "Which two countries border the United States on land?", a: ["Canada and Mexico", "Canada and Russia", "Mexico and Cuba", "Bahamas and Canada", "Haiti and Mexico"] },
            { q: "What is the predominant climate regime in the United States?", a: ["Humid subtropical", "Mediterranean", "Polar", "Tundra", "Monsoon"] },
            { q: "Which city is known for having the tallest building in the USA (the former Sears Tower)?", a: ["Chicago", "New York City", "Washington, D.C.", "Los Angeles", "Miami"] },
            { q: "What type of government does the United States have?", a: ["A federal republic", "A monarchy", "A theocracy", "A single-party state", "A military dictatorship"] },
            { q: "How often are presidential elections held in the United States?", a: ["Every four years", "Every three years", "Every five years", "Every six years", "Every two years"] },
            { q: "What is the capital of the United States?", a: ["Washington, D.C.", "New York City", "Chicago", "Los Angeles", "Philadelphia"] },
            { q: "Who was the first president of the United States?", a: ["George Washington", "John Adams", "Thomas Jefferson", "James Madison", "James Monroe"] },
            { q: "When was the Declaration of Independence proclaimed?", a: ["1776", "1789", "1492", "1912", "1861"] },
            { q: "Who took the oath of office after the assassination of President Kennedy?", a: ["Lyndon B. Johnson", "Robert F. Kennedy", "Martin Luther King Jr.", "John F. Kennedy", "Richard Nixon"] },
            { q: "What is the USA described as in terms of its political structure?", a: ["A federal union of fifty states", "A monarchy", "A single state", "A confederation of kingdoms", "A city-state"] },
            { q: "Which city is popularly known as the 'City of Brotherly Love'?", a: ["Philadelphia", "San Jose", "New York City", "Dallas", "Los Angeles"] },
            { q: "Which city is called the 'Capital of Silicon Valley'?", a: ["San Jose", "Philadelphia", "New York City", "San Francisco", "Seattle"] },
            { q: "How is New York City popularly called?", a: ["Big Apple", "City of Brotherly Love", "Capital of Silicon Valley", "Empire City", "Gateway to Antarctica"] },
            { q: "What is New Zealand’s national emblem worn by New Zealanders representing their country in sport?", a: ["Silver fern", "Kākā", "Kea", "Moa", "Haka"] },
            { q: "What is the name of New Zealand’s national rugby team?", a: ["All Blacks", "Tall Blacks", "Silver Ferns", "New Zealand Warriors", "Kiwis"] },
            { q: "What is New Zealand’s total land area?", a: ["268,680 square kilometres", "103,738 square miles", "1,600 kilometres", "4.1 million", "2,000 kilometres"] }
        ]
    },
    "lexicology": {
        title: "Лексикология (Lexicology)",
        data: [
            { q: "‘Kick the bucket’ is euphemistic word for________", a: ["Death", "Apologize", "Play", "Beg", "Question"] },
            { q: "One of the best-known Southern dialects is__________", a: ["Cockney", "Midland", "American", "RP", "North"] },
            { q: "The science of dictionary-compiling is called _________", a: ["Lexicography", "Lexicology", "Lexis", "Stylistics", "Morphology"] },
            { q: "_______ is a variety of a language which prevails in a district, with local peculiarities of vocabulary, pronunciation and grammar", a: ["A dialect", "A slang", "A term", "A metaphor", "A morpheme"] },
            { q: "How many main groups of dialects are there in GB?", a: ["5", "4", "6", "3", "7"] },
            { q: "_______ are used in everyday conversational speech both by cultivated and uneducated people of all age groups.", a: ["Colloquial words", "Professional words", "Literary words", "Slang words", "Historical words"] },
            { q: "What is American equivalent of the word ‘sweets’?", a: ["Candies", "Cookies", "Biscuits", "Mints", "Lollipops"] },
            { q: "_______are words which are no longer used in everyday speech, which have been ousted by their synonyms.", a: ["Archaisms", "Phraseologisms", "Neologisms", "Homonyms", "Antonyms"] },
            { q: "________are word-groups that cannot be made in the process of speech they exist in the language as ready-made units.", a: ["Phraseologisms", "Homonyms", "Archaisms", "Neologisms", "Antonyms"] },
            { q: "To native words belong ____________", a: ["Most of prepositions", "Study of meaning", "Study of word-building", "All of them", "Some adjectives"] },
            { q: "What is a Semasiology?", a: ["Study of meaning; semantics", "Study of sound", "Study of origin of language", "Study of word-formation", "Study of grammatical meaning"] },
            { q: "Which branch of lexicology deals with the meaning of words and other linguistic units?", a: ["Semasiology", "Lexical morphology", "Onomasiology", "word-formation", "Morphology"] },
            { q: "Semasiological approach _____________", a: ["Considering different meanings of the word, determining interrelations between them, as well as discovering semantic relations between different words", "Reverse of the semasiological approach; it starts from an object and consists in analyzing different words correlated with it", "The object which is given a name", "The one who gives a name to an object", "The process of giving instructions"] },
            { q: "The lexical meaning is______", a: ["Individual, unique", "Individual, standard", "General, standard", "General, unique", "Standard, unique"] },
            { q: "Grammatical meaning is_________", a: ["General, standard.", "Individual, standard", "Individual, unique", "General, unique", "Standard, unique"] },
            { q: "The part-of-speech meaning is_________.", a: ["Classification of lexical items into major word-classes and minor word classes.", "The one who gives a name to an object", "A new word from a syllable of the original word", "All answers are correct.", "None is correct"] },
            { q: "What are the three constituent parts (subsystems) of a language system?", a: ["The phonological system, the lexical system and the grammatical system", "The phonological system, the lexical system and the vocabulary system", "The phonological system, the phonetical system and the grammatical system", "The morphological and syntactical system, the lexical system and the grammatical system", "Only phonological system"] },
            { q: "The phonological system –", a: ["Determines the material (phonetically) appearance of its significative (i.e., meaningful) units.", "Is the whole set of naming means of language, that is, the vocabulary of words and stable word groups.", "Is the whole set of regularities, i.e., the set of rules (laws) determining the formation of utterances...", "Determines the material (phonetically) appearance of its significative (i.e., meaningless) units.", "Isn’t the whole set of naming means of language..."] },
            { q: "The lexical system_________________", a: ["is the whole set of naming means of language, that is, the vocabulary of words and stable word groups.", "Isn’t the whole set of naming means of language...", "isn’t the whole set of regularities...", "determines the material (phonetically) appearance...", "is the whole set of regularities..."] },
            { q: "The grammatical system____________", a: ["is the whole set of regularities, i.e., the set of rules (laws) determining the formation of utterances...", "is studied by lexicology", "is studied by phonology", "is studied by all linguistic discipline.", "is studied by lexicography"] },
            { q: "Linguistic unit can enter into relations of two different kinds. The are____________", a: ["Paragmatical and Syntagmatical", "predicative and attributive", "semantic and functional", "semantic, formal and functional", "formal and informal"] },
            { q: "Two or more words identical in sound-form but different in meaning,", a: ["homonyms", "paroxysm", "antonyms", "synonyms", "phraseologisms"] },
            { q: "There are three aspects of homonyms", a: ["sound-form, graphic-form and meaning", "grammatical, lexical, graphic", "semantic, lexical, lexico-grammatical", "lexical, lexico-grammatical, grammatical", "graphic-form and meaning"] },
            { q: "Homonyms are", a: ["words identical both in spelling and in sound-form but different in meaning", "words identical both in meaning and in spelling", "words different in sound.", "words identical in meaning but different in sound-form", "words different in meaning but identical in sound-form"] },
            { q: "Homophones _______", a: ["words identical in sound-form but different in spelling", "are same spelling, different pronunciation and different meanings.", "words identical both in meaning and in spelling", "lexical, lexico-grammatical, graphic", "words identical in spelling but different in sound-form"] },
            { q: "Homographs are________", a: ["words identical in spelling but different in sound-form.", "words sound alike", "words identical both in spelling and in sound-form but different in meaning", "All answers are correct.", "None is correct"] },
            { q: "Homonyms________", a: ["flat-flat; light-light; spring-spring;", "perform-reform; right-wright; day-night", "lead-lead; write-read; bow-bow", "spring-summer; steel-steal; sun-moon", "jeans-genes, know-now, but-bat"] },
            { q: "Lexicology is a branch of linguistics which deals with _____", a: ["lexical units and the vocabulary of a language", "the study of the nature, functions and structure of stylistic devices", "various means of expressing grammatical relations", "the outer sound form of the word", "only grammatical structure"] },
            { q: "The term lexicology comes from", a: ["a Greek word", "a French word", "a Latin word", "a German word", "an English word"] },
            { q: "The object of lexicology is _________", a: ["lexical units", "phonemes", "methods of lexical units’ investigation", "phonetical units", "morphological structure"] },
            { q: "LEXIS means_______", a: ["vocabulary", "phrase", "learning", "units", "study"] },
            { q: "Lexicology has close ties with___________", a: ["phonetics, grammar, history of a language, stylistics and sociolinguistics", "phonetics and grammar", "literature, history and sociology", "philosophy and history", "grammar and stylistics"] },
            { q: "What is special Lexicology?", a: ["It is the lexicology of a particular language", "It is the lexicology of any language", "the structural and semantic entity of language units within the language system", "the study of vocabulary at a certain time of its development", "the study of grammar structure"] },
            { q: "The word has _____________", a: ["phonological, semantic, syntactic aspects", "phonological and semantic aspects", "phonological and syntactic aspects", "phonological", "only semantic aspects"] },
            { q: "By external structure of the word we mean ___________", a: ["its morphological structure", "its meaning", "Paragmatical approach", "Syntagmatical approach", "phonological structure"] },
            { q: "Internal structure of the word is", a: ["its semantic structure", "its morphological structure", "its sound-form", "a grammar form", "phonological structure"] },
            { q: "Which branch of lexicology deals with meaning of words and other linguistic units?", a: ["Semasiology", "Lexical Morphology", "Onomasiology", "Phonology", "Stylistics"] },
            { q: "Choose the antonym the words 'to lose'.", a: ["to win", "to complete", "to explain", "to leave", "to play"] },
            { q: "Choose the definition to the word 'strange'", a: ["not known before; unfamiliar", "a very interesting fact", "a very important thing", "something very amusing and funny", "something awful"] },
            { q: "Choose the antonym the word 'noise'", a: ["silence", "cheer", "sail", "wait", "talk"] },
            { q: "Choose the word with the meaning 'послевоенный'", a: ["postwar", "prewar", "diswar", "underwar", "rewar"] },
            { q: "Choose the antonym the word 'allow'", a: ["forbid", "rub", "replay", "burn", "forget"] },
            { q: "Lexicology is ____________", a: ["the study of words", "the study of origin of language and words", "the study of mental processes and language", "the study of relations between the word and its referent", "the study of sounds"] },
            { q: "The fact that words are composed of component morphemes, which are permanently linked together, reflects_________.", a: ["the formal unity of the word", "the semantic unity of the word", "external structure of the word", "internal structure of the word", "grammar structure"] },
            { q: "Lexicology deals with ________", a: ["properties of words", "phonetic form", "grammatical meaning", "morphemes", "phraseologisms"] },
            { q: "What’s the other way of naming the descriptive lexicology?", a: ["synchronic lexicology", "morphology", "semasiology", "etymology", "phonology"] },
            { q: "The system formed by the sum of all the words and word equivalents is called:", a: ["vocabulary", "thematic group", "semantic grouping", "phraseological units", "grammar"] },
            { q: "How is the study of words and vocabulary irrespective of the specific features of any particular language is called?", a: ["general lexicology", "etymology", "historical lexicology", "diachronic lexicology", "synchronic lexicology"] },
            { q: "Which branch of linguistics deals with the origin and history of words?", a: ["etymology", "lexicography", "phonology", "morphology", "semasiology"] },
            { q: "How do we call the historical lexicology in other words?", a: ["diachronic lexicology", "synchronic lexicology", "morphology", "philological study", "etymology"] }
        ]
    },
    "business": {
        title: "Деловой английский (Business English)",
        data: [
            { q: "I heard of a new company today with which we should co-operate and____ business with.", a: ["do", "create", "make", "none", "have"] },
            { q: "Shortly after he was dismissed from the firm he decided to ______ himself up in his own business.", a: ["set", "place", "hold", "put", "none"] },
            { q: "She knew that there was some kind of______ business going on because strange things were happening.", a: ["funny", "weird", "unusual", "stupid", "none"] },
            { q: "We really can't delay any more with our plans and must _______ down to business as soon as possible.", a: ["get", "cut", "find", "set", "none"] },
            { q: "When the bomb went off, most of the injured were just ordinary people going______ their business.", a: ["about", "across", "along", "through", "none"] },
            { q: "I've warned you before that you shouldn't get involved in this matter and you have _____ business discussing it.", a: ["no", "not", "some", "little", "make"] },
            { q: "That's really not my concern at all and I'm certainly not___ the business of telling others what to do.", a: ["in", "out", "make", "of", "by"] },
            { q: "She was very enthusiastic about her new job and was making rapid progress_______ nobody's business.", a: ["like", "similar", "as", "with", "none"] },
            { q: "He was very keen that we kept in touch and for that reason he handed me his business_______", a: ["card", "ticket", "notice", "paper", "none"] },
            { q: "The whole site has nothing but offices and administration centres and that's why we call it a business ______", a: ["park", "situation", "field", "place", "none"] },
            { q: "The __________ line was shut down for two hours as a result of damaged machinery.", a: ["production", "delivery", "control", "market", "cancel"] },
            { q: "Information on __________ prices is available to brokers throughout the world.", a: ["market", "share", "trading", "delivery", "make"] },
            { q: "I am going to __________ my trip to New York. The situation changed completely.", a: ["cancel", "deny", "refuse", "respond", "do"] },
            { q: "The recent boom in consumer spending resulted in sales __________.", a: ["growth", "recession", "improvement", "make", "do"] },
            { q: "Hewlett Packard is known as one of the most reputable __________ in the electronic and computer industry.", a: ["suppliers", "customers", "buyers", "no", "make"] },
            { q: "What is the secret of their fantastic commercial __________ ?", a: ["success", "production", "market", "invoice", "no"] },
            { q: "A movement of money into or out of an account is called __________ .", a: ["transaction", "option", "invoice", "make", "do"] },
            { q: "We decided to __________ the new model at the trade fair in autumn.", a: ["launch", "manufacture", "no", "produce", "market"] },
            { q: "Our company is ready to sponsor the city football team if they wear our __________ on their shirts.", a: ["logo", "brand", "slogan", "no", "banner"] },
            { q: "The 1929 __________ market crash led to the great depression in many countries.", a: ["stock", "share", "stake", "store", "market"] },
            { q: "The CEO decided to ______ the outdated policy and introduce a new compliance framework.", a: ["phase out", "remove", "cancel", "stop", "change"] },
            { q: "Our marketing team needs to ______ creative solutions for the upcoming campaign.", a: ["come up with", "think of", "invent", "develop", "imagine"] },
            { q: "We must ______ the contract details before signing to avoid misunderstandings.", a: ["iron out", "solve", "settle", "fix", "repair"] },
            { q: "The project was temporarily ______ due to a lack of funding.", a: ["put on ice", "paused", "delayed", "stopped", "frozen"] },
            { q: "The company plans to ______ into emerging Asian markets next year.", a: ["break into", "enter", "penetrate", "expand", "move"] },
            { q: "The management team decided to ______ costs by cutting unnecessary expenditures.", a: ["cut back on", "reduce", "lessen", "limit", "lower"] },
            { q: "Our startup managed to ______ a niche market with its innovative product.", a: ["tap into", "reach", "access", "enter", "get"] },
            { q: "The CFO warned that any unforeseen expenses could ______ the budget.", a: ["throw off", "disrupt", "disturb", "ruin", "break"] },
            { q: "Before launching the product, the company decided to ______ consumer preferences.", a: ["drill down into", "analyze", "investigate", "look at", "research"] },
            { q: "The HR department is developing a ______ for senior leadership roles.", a: ["succession plan", "replacement schedule", "promotion plan", "career roadmap", "future plan"] },
            { q: "We need to ______ the quarterly report for errors before presenting it to the board.", a: ["go over", "check", "review", "inspect", "read"] },
            { q: "Investors are eager to ______ the company if it maintains strong growth.", a: ["buy out", "purchase", "acquire", "invest in", "get"] },
            { q: "The new regulations will ______ stricter reporting requirements for listed companies.", a: ["tighten up", "strengthen", "enforce", "increase", "add"] },
            { q: "The team must ______ all pending tasks before the end of the week.", a: ["follow up on", "check", "review", "complete", "finish"] },
            { q: "To stay competitive, the company must ______ technological innovations.", a: ["capitalize on", "take advantage of", "benefit from", "use", "employ"] },
            { q: "The company had to ______ bad debts that could not be recovered.", a: ["write off", "cancel", "erase", "delete", "forget"] },
            { q: "The board agreed to ______ the proposal until further analysis was completed.", a: ["table", "postpone", "pause", "delay", "wait"] },
            { q: "The management promised to ______ employee complaints promptly.", a: ["follow up on", "check", "investigate", "resolve", "listen"] },
            { q: "The project team must ______ the objectives before proceeding to the next phase.", a: ["stick to", "adhere to", "follow", "comply with", "respect"] },
            { q: "The scandal ______ the company’s reputation in the media.", a: ["tarnished", "damaged", "spoiled", "weakened", "broke"] },
            { q: "The manager encouraged the staff to ______ in problem solving sessions.", a: ["brainstorm", "think", "consider", "analyze", "discuss"] },
            { q: "The company decided to ______ from non-profitable business units.", a: ["divest", "sell", "withdraw", "dispose", "remove"] },
            { q: "The CEO promised that the company would ______ fraudulent activities.", a: ["clamp down on", "stop", "reduce", "control", "limit"] },
            { q: "The project manager must ______ the project to ensure timely completion.", a: ["see through", "oversee", "manage", "supervise", "lead"] },
            { q: "The company plans to ______ a new line of eco-friendly products next quarter.", a: ["roll out", "launch", "introduce", "release", "make"] },
            { q: "The board of directors asked for a ______ of all ongoing projects.", a: ["comprehensive review", "thorough analysis", "full report", "complete check", "look"] },
            { q: "To improve efficiency, the company decided to ______ the production process.", a: ["streamline", "simplify", "organize", "enhance", "fix"] },
            { q: "The new product ______ last month and received positive customer feedback.", a: ["hit the market", "entered the market", "was launched", "appeared", "came out"] },
            { q: "The company’s innovative solutions helped it ______ of the curve in the tech industry.", a: ["stay ahead", "lead", "outperform", "win", "be top"] },
            { q: "The financial analyst presented a ______ of projected cash flows for the next fiscal year.", a: ["breakdown", "summary", "report", "overview", "list"] }
        ]
    },
    "phonetics": {
        title: "Фонетика (Phonetics)",
        data: [
            { q: "The vocal cords and the glottis constitute:", a: ["Vibrator mechanism", "Resonator mechanism", "Power mechanism", "Obstructor mechanism", "They don’t constitute any mechanisms"] },
            { q: "Which tendency that determines the place and the different degree of word- stress, results in placing the word-stress on the initial syllable?", a: ["Semantic factor", "Communicative", "Retentive tendency", "Rhythmic tendency", "Recessive tendency"] },
            { q: "Phonetic is an independent branch of:", a: ["Linguistics", "Lexicology", "Stylistics", "Grammar", "Logic"] },
            { q: "A syllable which begins in vowel sound is called:", a: ["Uncovered", "Closed", "Covered", "Open", "Fixed"] },
            { q: "Allophones are:", a: ["Variants of phonemes", "Phonemes themselves", "Morphemes", "Non-distinctive sounds", "Any sounds"] },
            { q: "The terminal tone is:", a: ["The last stressed word", "The first stressed word", "The unstressed word preceding the first stressed word", "The unstressed words with the last stressed word", "All unstressed words in an intonation-group"] },
            { q: "What obstructor mechanism responsible for?", a: ["For the production of consonants", "For the production of vowels", "For the production of sonorants only", "For the production of all the sounds", "For the production of nasal sounds"] },
            { q: "What functions does Intonation perform?", a: ["Constitute, distinctive and recognitive", "Rhythmical and accentual", "Constitutive, recessive, retentive", "Identificatory, rhythmic and fixed", "Segmental and supra-segmental"] },
            { q: "The first stressed word in an intonation group is:", a: ["The head", "The pre-head", "The scale", "The nucleus", "The tail"] },
            { q: "What type of word-stress does the English accentual structure belong to?", a: ["Dynamic", "Quantitative", "Musical", "Quantitative, qualitative and dynamic", "Qualitative only"] },
            { q: "What organs of speech belong to the vibrator mechanism?", a: ["The vocal cords and the glottis", "The nasal cavity", "The lungs, the windpipe, the glottis, the pharynx", "The alveoli", "The teeth"] },
            { q: "Assimilated sound is:", a: ["When the articulation of a sound is modified under the influence of the neighboring sound", "The consonant sound at the end of the word", "The sound written in transcription", "Any sound in the open syllable", "The result of two neighboring vowels"] },
            { q: "In the case when the assimilated consonant is influenced by the preceding consonant we have:", a: ["Progressive assimilation", "Regressive assimilation", "Double assimilation", "Complete assimilation", "Incomplete"] },
            { q: "What directions of assimilation do you know?", a: ["Progressive, reciprocal and regressive", "Complete and incomplete", "Progressive and reciprocal", "Regressive and reciprocal", "Double and regressive"] },
            { q: "Which theory of syllable is based on L.V. Shcerba’s statement?", a: ["Muscular tension theory", "Sonority theory", "Are of loudness theory", "Expiratory theory", "Theory of relativity"] },
            { q: "What branch of phonetics studies the functional aspect of speech sounds?", a: ["Phonology", "Physiological phonetics", "Acoustic phonetic", "General phonetics", "Comparative phonetics"] },
            { q: "What branch of phonetics studies the articulatory and auditory aspect of speech sounds?", a: ["Physiological phonetics", "Phonology", "Acoustic phonetics", "General phonetics", "Comparative phonetics"] },
            { q: "The stress which serves to make especially prominent certain parts of the utterance called:", a: ["Emphatic", "Logical", "Syntagmatic", "Hesitation", "Syntactic"] },
            { q: "Modification of consonants under the influence of vowels is called:", a: ["Accommodation", "Assimilation", "Lateral plosion", "Elision", "Loss of plosion"] },
            { q: "What type is the syllable 'no'?", a: ["Covered, open", "Covered, close", "Uncovered, close", "Uncovered, open", "Ubcovered, covered"] },
            { q: "Speech is impossible without the following mechanisms:", a: ["The resonator and the obstructor mechanisms", "Speech is impossible without all these mechanisms", "The power and the vibrator mechanisms", "Careless speech is possible without all these mechanisms", "Only the obstructor mechanisms"] },
            { q: "Where does the stress fall in the words “psychology, biologist”:", a: ["On the 2-d syllable", "On the 3-d syllable from the end", "On the last syllable", "They are unstressed words", "On the 1-st syllable"] },
            { q: "What is the oldest and the most developed branch of phonetics?", a: ["Physiological phonetics", "Phonology", "Acoustic phonetics", "General phonetics", "Comparative phonetics"] },
            { q: "What intonational function manifests itself in the fact than each syllable in the sentence has a certain pitch and can’t exist without it?", a: ["Constitutive function", "Distinctive function", "Recognitive function", "Principal function", "All of them"] },
            { q: "What is the unit of Phonetics?", a: ["A distinctive speech sound", "An allophone", "Minimal pairs", "A phoneme", "A speech sound"] },
            { q: "English, Russian, German languages are traditionally considered to belong to:", a: ["Dynamic", "Musical", "Qualitative", "Dynamic, qualitative, quantitative", "Quantitative"] },
            { q: "What are the English nasal consonants?", a: ["[m], [n], [η]", "[m], [p], [d]", "[p], [b], [d], [t], [k]", "[], [n], [l]", "[m], [n], [l], [], [r]"] },
            { q: "Correlative in the time of stressed and unstressed syllable in intonation group is:", a: ["Rhythm", "Melody", "Timber", "Tempo", "Pause"] },
            { q: "What do we call syllable in writing?", a: ["Syllabographs", "Morphemes", "Syllabophones", "Phonemes", "Suffixes"] },
            { q: "Three degree of word stress are suggested by:", a: ["American linguists", "British and Russian linguists", "British physiologists", "Baudouin de Courteney", "L.V. Shcherba"] },
            { q: "Modification of consonants under the influence of a consonant is called:", a: ["Assimilation", "Adaptation", "Accommodation", "Elision", "Loss of plosion"] },
            { q: "What forms the speed of speech?", a: ["Tempo", "Pitch and loudness", "Rhythm", "Loudness", "Pausation"] },
            { q: "What is the oldest theory of syllable formation and syllable division?", a: ["Expiratory theory", "Sonority theory", "Muscular tension theory", "The 'are of loudness' theory", "musical"] },
            { q: "What is the unit of Phonology?", a: ["A phoneme", "A morpheme", "A sound", "Syllable", "Word"] },
            { q: "What resonator mechanism is responsible for the articulation of vowels?", a: ["Oral together with nasal resonator", "Oral resonator", "Nasal resonator", "Resonator mechanisms are not responsible for it", "Nasal resonator and the vocal cords"] },
            { q: "What is Received Pronunciation?", a: ["Standard English", "English, spoken by foreign learners of the language", "English, spoken in the USA", "Standard American", "All types of pronunciation in G.B."] },
            { q: "A special prominence given to one more syllable in a word is:", a: ["The stress", "The rhythm", "The melody", "The tempo", "The pause"] },
            { q: "What is a syllable?", a: ["The shortest segment of speech sounds", "Segmental structure of the word", "One of the speech sounds", "Morphemic structure of the word", "Shortest speech continuum"] },
            { q: "Phonetics studies:", a: ["Sounds and their various aspects and functions", "Words and their semantic structure", "Words and their relations in the sentence", "Parts of speech", "Morphological structure of sentences"] },
            { q: "What is the definition of assimilation?", a: ["The influence of neighboring consonants to each other", "The result of obstruction", "The result of adaptation of one vowel to another", "The result of length", "The result of softness of consonants"] },
            { q: "Which phrase demonstrates flapping of /t/ in General American pronunciation?", a: ["“better” → /ˈbɛɾәr/", "“tight” → /taɪt/", "“take it” → /teɪk ɪt/", "“tall man” → /tɔːl mæn/", "“want to” → /wɒnt tuː/"] },
            { q: "In which example is the vowel completely reduced to /ә/?", a: ["“adapt” → /әˈdæpt/", "“support” → /sәˈpɔːt/", "“about” → /әˈbaʊt/", "“ago” → /әˈɡәʊ/", "“arrive” → /әˈraɪv/"] },
            { q: "Which sentence contains intonation break before the subordinate clause?", a: ["“I think | he’ll come later.”", "“This is the man who helped me.”", "“I don’t know when he left.”", "“Tell me what you need.”", "“He said that he was tired.”"] },
            { q: "Which example shows palatalization of the final consonant?", a: ["“did you” → /dɪdʒu/", "“bad cat” → /bæd kæt/", "“take care” → /teɪk keә/", "“love you” → /lʌv juː/", "“five years” → /faɪv jɪәz/"] },
            { q: "In which phrase is /h/ most likely to be elided in rapid connected speech?", a: ["“Tell him” → /tel ɪm/", "“help her” → /help hɜː/", "“hold on” → /hәʊld ɒn/", "“How is it?” → /haʊ ɪz ɪt/", "“Happy hour” → /ˈhæpi aʊә/"] },
            { q: "Which phrase shows devoicing of a voiced consonant at the end of a word?", a: ["“dog” → /dɒk/", "“big one” → /bɪɡ wʌn/", "“move on” → /muːv ɒn/", "“leave it” → /liːv ɪt/", "“cab owner” → /kæb әʊnә/"] },
            { q: "Which of these stress patterns is correct for a phonologically conditioned shift?", a: ["“thirteen men” → /ˌθɜːˈtiːn men/", "“thirteen books” → /θɜːˈtiːn bʊks/", "“fourteen pages” → /fɔːˈtiːn peɪdʒiz/", "“fifteen girls” → /fɪfˈtiːn ɡɜːlz/", "“sixteen hours” → /sɪksˈtiːn aʊәz/"] },
            { q: "Which of the following uses a fall-rise tone?", a: ["“I liked it…” (implying “but…”)", "“Sit down.”", "“What is your name?”", "“Where are you?”", "“Take this.”"] },
            { q: "Which variant shows dark L?", a: ["“full” → /fʊɫ/", "“lamp” → /læmp/", "“lake” → /leɪk/", "“light” → /laɪt/", "“loud” → /laʊd/"] },
            { q: "Which example demonstrates linking V-V (vowel-to-vowel linking)?", a: ["“go away” → /ɡәʊ‿әˈweɪ/", "“five o’clock”", "“take off”", "“two people”", "“see those”"] }
        ]
    },
    "grammar": {
        title: "Грамматика (Theoretical Grammar)",
        data: [
            { q: "Choose the right form: If only he … the truth earlier, none of this would have happened.", a: ["had known", "knows", "would know", "had known", "knew"] },
            { q: "Choose the right variant of the Reported Speech: 'The girl asked her friend...'", a: ["The girl asked her friend to help her with the exercise", "The girl asked her friend help her with the exercise", "The girl told her friend to help her with the exercise", "The girl asked her friend helping her with the exercise", "The girl asked her friend to helping her with the exercise"] },
            { q: "Fill in the blank: My sister is as … as my brother.", a: ["tall", "taller", "tallest", "most tall", "more tall"] },
            { q: "Fill in the blank: The company approved the … plan yesterday.", a: ["manager's", "managers'", "managers", "manager", "managers’s"] },
            { q: "Finish the question: Susan has got to mark this test later, ...?", a: ["hasn't she", "has she", "does she", "isn't she", "doesn't she"] },
            { q: "Change the underlined word: He can speak English very well.", a: ["is able to", "must", "would", "ought", "has to"] },
            { q: "Choose the right order of the words:", a: ["She didn’t understand what the teacher meant.", "What meant the teacher she didn’t understand.", "She didn’t understand the teacher what meant.", "What the teacher she didn’t understand meant.", "The teacher didn’t understand what she meant."] },
            { q: "Put the sentence into Passive Voice (Future): The project...", a: ["will be finished next week", "has been finished next week", "will have finished next week", "is finished next week", "They will be finished the project next week"] },
            { q: "Finish the sentence: Don't work too hard! Take care of...!", a: ["yourself", "myself", "your", "you", "me"] },
            { q: "Match the sentence with the time: I have been working on this project …", a: ["since last Monday", "yesterday", "tomorrow", "in 2010", "last week"] },
            { q: "Choose the right form: If he … harder, he would have passed the exam.", a: ["had studied", "studies", "studied", "has studied", "was studying"] },
            { q: "Choose the right form: We asked if he ... to join us.", a: ["wanted", "will want", "wants", "has wanted", "is wanting"] },
            { q: "Say it in Passive Voice: Nobody lived in that old house.", a: ["That old house was not lived in.", "That old house lived nobody in.", "In that old house was not lived.", "Nobody was lived in that old house.", "In that old house nobody lived in."] },
            { q: "Fill in the blank: This house is ... of all the houses in the street.", a: ["the newest", "as new as", "new", "the most new", "newer"] },
            { q: "Finish the question: Helen didn't say that, ...?", a: ["did she", "didn't she", "didn't Helen", "said she", "did Helen"] },
            { q: "Make the right choice: He has left ... Astana ... Moscow: his family is already in Russia.", a: ["from / for", "-/for", "-/to", "from / to", "for/-"] },
            { q: "Fill the articles in: On ... Sunday our family went to ... country ... last week.", a: ["-/the/-", "a/the/-", "-/-/the", "a/-/a", "the/a/-"] },
            { q: "Choose the right variant of the Reported Speech: 'Are you fond of going to the theatre?' asked my friend.", a: ["My friend asked if I was fond of going to the theatre.", "My friend asked if you are fond of going to the theatre.", "My friend asked if I had been fond of going to the theatre.", "My friend asked if I would be fond of going to the theatre.", "My friend asked if I am fond of going to the theatre."] },
            { q: "Match the sentence with the time: I had been doing my homework ...", a: ["for 3 hours at 5 o'clock yesterday", "at 3 o'clock yesterday", "by 3 o'clock yesterday", "for 3 hours yesterday", "already at 5 o'clock yesterday"] },
            { q: "Make the right choice: John ... not tell us the rules of the game: we know them.", a: ["need", "must", "have to", "does", "should"] },
            { q: "Fill in the blank: Kate is ... her brother.", a: ["as lazy as", "as lazier as", "lazier", "the laziest", "the most lazy"] },
            { q: "Make the right choice: The translation of this article ... by next Tuesday.", a: ["will have been finished", "will have finished", "will finish", "will be finished", "will be finishing"] },
            { q: "Choose the right form: The train ... when they got to the station.", a: ["had already left", "was left", "has already left", "is leaving", "will already leave"] },
            { q: "Fill the prepositions in: France is ... the south-west ... Europe.", a: ["in, of", "on, of", "to, of", "in, to", "-, of"] },
            { q: "Choose the correct variant (conditionals): He is not ill: if he (to be) ill, he (not to play) tennis so much.", a: ["He is not ill: if he were ill, he would not play tennis so much.", "He is not ill: if he had been ill, he would not have played tennis so much.", "He is not ill: if he will be ill, he is not play tennis so much.", "He is not ill: if he are ill, he will not play tennis so much.", "He is not ill: if he is ill, he will not play tennis so much."] },
            { q: "Fill the articles in: We go to ... school in ... morning.", a: ["- / the", "a/-", "the / the", "a / the", "the / -"] },
            { q: "Choose the variant that can't be used in the sentences. You ________ many questions.", a: ["didn't be asked", "aren’t asked", "haven’t been asked", "weren't asked", "won't be asked"] },
            { q: "Make the right choice: Paul's hands are dirty. He ... the car for two hours already.", a: ["has been repairing", "is repairing", "repairs", "repaired", "has repaired"] },
            { q: "Choose the correct variant (conditionals): I wish I (not to drink) so much coffee...", a: ["I wish I had not drunk so much coffee in the evening...", "I wish I do not drink so much coffee in the evening...", "I wish I were not drink so much coffee in the evening...", "I wish I would not drink so much coffee in the evening...", "I wish I am not drink so much coffee in the evening..."] },
            { q: "Choose the right order of words:", a: ["We went to school very quickly that morning.", "We went very quickly to school that morning.", "Very quickly we went to school that morning.", "That morning we went to very quickly school.", "We went that morning very quickly to school."] },
            { q: "Fill in the blank: That building ... than that one.", a: ["higher", "as high as", "more high", "the highest", "the most high"] },
            { q: "Choose the correct variant (conditionals): How slippery it is! If it (not to rain), it (not to be) slippery.", a: ["How slippery it is! If it had not rained, it would not be slippery.", "How slippery it is! If it did not rained, it would not be slippery.", "How slippery it is! If it will not rain, it had not been slippery.", "How slippery it is! If it were not rain, it will not be slippery.", "How slippery it is! If it did not rain, it would not be slippery."] },
            { q: "Make the right choice: He was told that a married couple ... in the house for the last 3 years.", a: ["had been living", "would live", "were living", "will live", "had lived"] },
            { q: "Finish the sentence: He is very selfish. He only thinks of...", a: ["himself", "hiself", "he", "his", "him"] },
            { q: "Choose the right order of words:", a: ["She was not playing the piano when her mother came.", "The piano she was not playing when her mother came.", "She was not playing the piano when came her mother.", "She not was playing the piano when her mother came.", "She was playing the piano when her mother not came."] },
            { q: "Make the right choice: He's got a lung problem and he ... go to hospital every two weeks.", a: ["has to", "can", "may", "should", "must"] },
            { q: "Choose the correct form (wish / regret, past perfect): I wish I … that exam last week; it was much harder than I expected.", a: ["had passed", "passed", "would pass", "have passed", "were passing"] },
            { q: "Choose the correct conditional (third conditional): If she … earlier, she wouldn’t have missed the train.", a: ["had left", "left", "would leave", "was leaving", "has left"] },
            { q: "Passive voice with modals: The instructions … read carefully before starting the experiment.", a: ["must be", "must", "should be", "should", "have to"] },
            { q: "Reported speech (complex tense change): He said, “I have been working on this project since Monday.”", a: ["He said that he had been working on this project since Monday.", "He said that he has been working on this project since Monday.", "He said that he was working on this project since Monday.", "He said that he will be working on this project since Monday.", "He said that he would work on this project since Monday."] },
            { q: "Choose the correct comparative / superlative construction: This solution is far … than the one we discussed yesterday.", a: ["more effective", "effectiver", "as effective as", "the most effective", "most effective"] },
            { q: "Choose the correct time expression to complete the sentence: I will have finished my report …", a: ["by Monday", "tonight", "one of those days", "lately", "till 3 yesterday"] },
            { q: "Fill in the blank: Lucy is ... her brother.", a: ["as lazy as", "the most lazy", "as lazier as", "the laziest", "lazier"] },
            { q: "Make the right choice of the possessive case:", a: ["my mother's dresses", "mine mother dress", "my mother's dress's", "my mothers' dress", "mine mother dresses"] },
            { q: "Make the right choice: Paul ... not tell us the rules of the game: we know them.", a: ["need", "should", "does", "have to", "must"] },
            { q: "Choose the correct form (perfect infinitive / gerund): She seems … the instructions carefully before starting.", a: ["to have read", "having read", "to read", "read", "have read"] },
            { q: "Choose the correct tense (Future in the Past): He promised that he … the report by Friday.", a: ["would finish", "will finish", "finished", "had finished", "finishes"] },
            { q: "Correct use of participles / reduced clauses: … by the sudden noise, everyone in the office jumped.", a: ["Startled", "Being startled", "Startling", "Having startled", "Being startling"] },
            { q: "Choose the correct modal for past deduction: He … have left already; his car isn’t in the parking lot.", a: ["must", "must have", "might", "might have", "should"] },
            { q: "Choose the correct sequence of tenses (mixed conditionals): If I … more time yesterday, I would be able to finish this task today.", a: ["had had", "have", "had", "would have", "have had"] }
        ]
    }
};